# Generated by Django 5.2.12 on 2026-03-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount paid upfront (50% advance)', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Balance due on delivery', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='remaining_paid',
            field=models.BooleanField(default=False, help_text='True when balance collected on delivery'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('cod', 'Cash on Delivery'), ('custom_advance', 'Custom Cake Advance')], default='razorpay', max_length=20),
        ),
    ]
