# Generated by Django 5.2.12 on 2026-03-14 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery_slots', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotbooking',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slot_booking', to='orders.order'),
        ),
        migrations.AddField(
            model_name='slotbooking',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_bookings', to='delivery_slots.deliveryslot'),
        ),
    ]
