# Generated by Django 5.2.12 on 2026-03-14 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('order_placed', 'Order Placed'), ('order_confirmed', 'Order Confirmed'), ('order_preparing', 'Order Being Prepared'), ('order_dispatched', 'Order Dispatched'), ('order_out_for_delivery', 'Order Out for Delivery'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('payment_success', 'Payment Success'), ('custom_cake_received', 'Custom Cake Request Received'), ('custom_cake_quoted', 'Custom Cake Quoted'), ('low_stock', 'Low Stock Alert'), ('promotional', 'Promotional')], max_length=50, unique=True)),
                ('email_subject', models.CharField(blank=True, max_length=200)),
                ('email_body', models.TextField(blank=True, help_text='Use {variable} for substitution.')),
                ('sms_body', models.CharField(blank=True, max_length=160)),
                ('whatsapp_body', models.TextField(blank=True)),
                ('push_title', models.CharField(blank=True, max_length=100)),
                ('push_body', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('push', 'Push')], max_length=20)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
