# Generated by Django 5.2.12 on 2026-04-03 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('campaign_type', models.CharField(choices=[('birthday', 'Birthday'), ('festival', 'Festival / Seasonal'), ('promotional', 'Promotional'), ('custom', 'Custom')], default='promotional', max_length=20)),
                ('channel', models.CharField(choices=[('email', 'Email only (Free)'), ('whatsapp', 'WhatsApp only (₹0.30-0.70/msg)'), ('both', 'Email + WhatsApp'), ('push', 'Push only (Free)')], default='email', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('subject', models.CharField(blank=True, help_text='Email subject line', max_length=200)),
                ('email_body', models.TextField(blank=True, help_text='Use {name}, {coupon_code}, {discount}, {valid_days}')),
                ('whatsapp_msg', models.TextField(blank=True, help_text='Use {name}, {coupon_code}, {discount}, {valid_days}')),
                ('push_title', models.CharField(blank=True, max_length=100)),
                ('push_body', models.CharField(blank=True, max_length=200)),
                ('include_coupon', models.BooleanField(default=False)),
                ('coupon_discount', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('coupon_type', models.CharField(choices=[('percentage', 'Percentage'), ('flat', 'Flat')], default='percentage', max_length=20)),
                ('coupon_valid_days', models.PositiveIntegerField(default=7)),
                ('coupon_prefix', models.CharField(default='CAKE', max_length=10)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
